export const projects = [
  {
    title: 'Administração',
    description: "• Presencial • Digital EAD • flex",
      image: '/images/1.png',
      tags: ['Curso superior tradicional'],
      visit: 'https://unip.br/cursos/graduacao/tradicionais/administracao.aspx',
    id: 1,
  },
  {
    title: 'Análise e Desenvolvimento de Sistemas',
    description: "• Presencial • Digital EAD",
      image: '/images/1.png',
      tags: ['Curso Superior de Tecnologia'],
      visit: 'https://unip.br/cursos/graduacao/tecnologicos/analise_desenvolvimento_sistemas.aspx',
    id: 2,
  }, {
    title: 'Artes Visuais',
    description: "Digital EAD",
      image: '/images/1.png',
      tags: ['Curso superior tradicional'],
      visit: 'https://unip.br/cursos/graduacao/tradicionais/artes_visuais.aspx',
    id: 3,
  },
   {
    title: 'Biomedicina',
    description: "• Presencial • Flex",
      image: '/images/1.png',
      tags: ['Curso Superior Tradicional'],
      visit: 'https://unip.br/cursos/graduacao/tradicionais/biomedicina.aspx',
    id: 4,
  },
  {
    title: 'Ciência da Computação',
    description:"• Presencial • Digital EAD",
    image: '/images/2.png',
    tags: ['Curso Superior Tradicional'],
    visit: 'https://unip.br/cursos/graduacao/tradicionais/ciencia_computacao.aspx',
    id: 5,
  },
  {
    title: 'Ciências Biológicas (Licenciatura)',
    description: "• Presencial • Flex",
      image: '/images/3.jpg',
      tags: ['Curso Superior Tradicional'],
    visit: 'https://unip.br/cursos/graduacao/tradicionais/ciencias_biologicas_licenciatura.aspx',
    id: 6,
  },
  {
    title: 'Ciências Contábeis',
    description: "• Presencial • Digital EAD • flex",
    image: '/images/4.jpg',
    tags: ['Curso Superior Tradicional'],
    visit: 'https://unip.br/cursos/graduacao/tradicionais/ciencias_contabeis.aspx',
    id: 7,
  },
  {
    title: 'Ciências Econômicas',
    description: "• Presencial • Digital EAD",
    image: '/images/4.jpg',
    tags: ['Curso Superior Tradicional'],
    visit: 'https://unip.br/cursos/graduacao/tradicionais/ciencias_economicas.aspx',
    id: 8,
  },
  {
    title: 'Comércio Exterior',
    description: "• Presencial • Digital EAD",
    image: '/images/4.jpg',
    tags: ['Curso Superior de Tecnologia'],
    visit: 'https://unip.br/cursos/graduacao/tecnologicos/comercio_exterior.aspx',
    id: 9,
  },
  {
    title: 'Design de Interiores',
    description: "• Presencial • Digital EAD",
    image: '/images/4.jpg',
    tags: ['Curso Superior de Tecnologia'],
    visit: 'https://unip.br/cursos/graduacao/tecnologicos/design_interiores.aspx',
    id: 10,
  },
  {
    title: 'Educação Física (Graduação Plena)',
    description: "• Presencial • Flex",
    image: '/images/4.jpg',
    tags: ['Curso Superior Tradicional'],
    visit: 'https://unip.br/cursos/graduacao/tecnologicos/comercio_exterior.aspx',
    id: 11,
  },
  {
    title: 'Empreendedorismo',
    description: "• Digital EAD",
    image: '/images/4.jpg',
    tags: ['Curso Superior de Tecnologia'],
    visit: 'https://unip.br/cursos/graduacao/tecnologicos/empreendedorismo.aspx',
    id: 12,
  },
  {
    title: 'Enfermagem',
    description: "• Presencial • Flex",
    image: '/images/4.jpg',
    tags: ['Curso Superior Tradicional'],
    visit: 'https://unip.br/cursos/graduacao/tradicionais/enfermagem.aspx',
    id: 13,
  },
  {
    title: 'Engenharia Civil',
    description: "• Presencial • Flex",
    image: '/images/4.jpg',
    tags: ['Curso Superior Tradicional'],
    visit: 'https://unip.br/cursos/graduacao/tradicionais/engenharia_civil.aspx',
    id: 14,
  },
  {
    title: 'Engenharia de Produção',
    description: "• Presencial • Flex",
    image: '/images/4.jpg',
    tags: ['Curso Superior Tradicional'],
    visit: 'https://unip.br/cursos/graduacao/tradicionais/engenharia_producao.aspx',
    id: 15,
  },
];

export const TimeLineData = [
  { year: "Lucas Ribeiro", text: 'O polo inicia a sua jornada', },
  { year: "Duda Pimentel", text: 'Mais de 300 alunos matriculados', },
  { year: "Ingrid Guga", text: 'Nossa equipe aumenta', },
  { year: "Rena Gonçalves", text: 'Mais de 500 alunos matriculados', },
  { year: 2021, text: 'Vencemos todos os desafios', },
  { year: 2022, text: 'Continuamos com a excelência UNIP', },
];